[package]
name = "multisig-prover-api"
version = "1.0.0"
rust-version = { workspace = true }
license = { workspace = true }
edition = { workspace = true }

[dependencies]
axelar-wasm-std = { workspace = true, features = ["derive"] }
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
multisig = { workspace = true, features = ["library"] }
router-api = { workspace = true }
sha3 = { workspace = true }

[dev-dependencies]
goldie = { workspace = true }

[lints]
workspace = true
