name: 'Setup Rust'
description: 'Install Rust toolchain from rust-toolchain.toml with Blacksmith-optimized caching'
inputs:
  cache-key:
    description: 'Cache namespace (e.g., "tests", "lints")'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Setup Rust toolchain
      id: rust
      uses: actions-rust-lang/setup-rust-toolchain@fb51252c7ba57d633bc668f941da052e410add48 # v1
      with:
        # Use Blacksmith cache instead of default Swatinem
        cache: false
        # Preserve RUSTFLAGS from .cargo/config.toml
        rustflags: ""

    # The default fallback is "stable", independent of the rust-toolchain.toml, and could be outdated.
    - name: Set active toolchain as default fallback
      shell: bash
      run: rustup default "$(rustup show active-toolchain | cut -d' ' -f1)"

    - name: Show installed versions
      id: versions
      run: |
        echo "rustc --version: $(rustc --version)"
        echo "cargo --version: $(cargo --version)"
        echo "rustup --version: $(rustup --version)"
        echo "cachekey=$(rustc --version | sed -E 's/[^0-9]+([0-9]+)\.([0-9]+)\.([0-9]+).*/\1\2\3a/' )" >> $GITHUB_OUTPUT
        echo "all installed toolchains:"
        echo "---------------------"
        rustup show
        echo "---------------------"
      shell: bash

    - name: Cache Rust dependencies
      uses: useblacksmith/rust-cache@f53e7f127245d2a269b3d90879ccf259876842d5 # v3.0.1
      id: cache
      with:
        # Automatic toolchain-based separation
        prefix-key: "${{ steps.rust.outputs.cachekey }}-rust"
        shared-key: "${{ inputs.cache-key }}"
        cache-on-failure: true

    - name: Log crates.toml on cache hit
      if: steps.cache.outputs.cache-hit == 'true'
      shell: bash
      run: |
        echo "Cache hit for key: ${{ steps.cache.outputs.cache-matched-key }}"
        cat /home/runner/.cargo/.crates.toml || true
