tm_jsonrpc="http://devnet-amplifier.axelar.dev:26657"
tm_grpc="tcp://devnet-amplifier.axelar.dev:9090"
event_buffer_cap=10000
health_check_bind_addr="0.0.0.0:3001"

[grpc]
ip_addr="127.0.0.1"
port=9091
global_concurrency_limit=1024
concurrency_limit_per_connection=32
request_timeout="30s"

[event_processor]
retry_delay="1s"
retry_max_attempts=3
stream_timeout="3s"
stream_buffer_size=100000
delay="2s"

[service_registry]
cosmwasm_contract="axelar1c9fkszt5lq34vvvlat3fxj6yv7ejtqapz04e97vtc9m5z9cwnamq8zjlhz"

[rewards]
cosmwasm_contract="axelar1c6d75nxssc8t62cgx28clqyd669g2uyymljeqw7hfsq3de3vt2zs5rvk8c"

[broadcast]
batch_gas_limit="20000000"
broadcast_interval="1s"
chain_id="devnet-amplifier"
gas_adjustment="2"
gas_price="0.00005uamplifier"
queue_cap="1000"
tx_fetch_interval="1000ms"
tx_fetch_max_retries="15"

[tofnd_config]
batch_gas_limit="10000000"
key_uid="axelar"
party_uid="ampd"
url="http://127.0.0.1:50051"

[tofnd_config.timeout]
secs=3
nanos=0

[[handlers]]
type="MultisigSigner"
cosmwasm_contract="axelar19jxy26z0qnnspa45y5nru0l5rmy9d637z5km2ndjxthfxf5qaswst9290r"
chain_name="avalanche-fuji"

[[handlers]]
type="EvmMsgVerifier"
cosmwasm_contract="axelar1252ahkw208d08ls64atp2pql4cnl9naxy7ahhq3lrthvq3spseys26l8xj"
chain_name="avalanche-fuji"
chain_rpc_url="https://red-divine-dream.avalanche-testnet.quiknode.pro/fe8a71d7e75a6fce0f2232361b795745ae818f6a/ext/bc/C/rpc"
chain_finalization="RPCFinalizedBlock"
