[package]
name = "chain-codec-api"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[features]
# Enable this if you use the multisig-prover contract compiled with this feature and need to receive
# the full message payloads.
receive-payload = []
# Enable this if you want to get notified after a signing session is created.
# Please note that you also need to use the multisig-prover contract that was compiled with this feature.
notify-signing-session = []

[dependencies]
axelar-wasm-std = { workspace = true }
client = { workspace = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
cw-storage-plus = { workspace = true }
error-stack = { workspace = true }
msgs-derive = { workspace = true }
multisig = { workspace = true, features = ["library"] }
multisig-prover-api = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
