[package]
name = "ton-utils"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axelar-wasm-std = { workspace = true, features = ["derive"] }
cosmwasm-std = "2.1.4"
error-stack = { workspace = true }
itertools.workspace = true
multisig = { workspace = true, features = ["library"] }
num-bigint = "0.4.6"
num-traits = { workspace = true }
router-api = { workspace = true }
sha3 = { workspace = true }
tonlib-core = "0.24.6"

[lints]
workspace = true
