[package]
name = "aleo-gmp-types"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
aleo-gateway-types = { workspace = true }
aleo-string-encoder = { workspace = true }
axelar-wasm-std = { workspace = true }
bytemuck = { workspace = true }
cosmwasm-std = { workspace = true }
error-stack = { workspace = true }
interchain-token-service-std = { workspace = true }
multisig = { workspace = true, features = ["library"] }
plaintext-trait = { workspace = true }
router-api = { workspace = true }
serde = { workspace = true }
snarkvm-cosmwasm = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
