[package]
name = "error-utils"
version = "1.0.0"
edition = "2021"
rust-version = { workspace = true }

[features]
eyre = ["dep:eyre"]
contracts = ["dep:error-utils-derive"]

[dependencies]
cosmwasm-std = { workspace = true }
cw2 = { workspace = true }
error-stack = { workspace = true }
error-utils-derive = { workspace = true, optional = true }
eyre = { workspace = true, optional = true }
itertools = { workspace = true }
thiserror = { workspace = true }
valuable = { workspace = true, features = ["derive"] }

[lints]
workspace = true
