[package]
name = "connection-router-api"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cosmwasm-schema = { workspace = true}
cosmwasm-std = { workspace = true}
cw-storage-plus = { workspace = true}
thiserror = {workspace = true}
axelar-wasm-std = {workspace = true}
error-stack = {workspace = true}
regex = "1.10.0"
serde_json = { workspace = true}
flagset = { version = "0.4.3", features = ["serde"] }
serde = {workspace = true}
schemars = {workspace = true}