[package]
name = "event-verifier-api"
version = "1.1.0"
rust-version = { workspace = true }
license = "MIT OR Apache-2.0"
edition = { workspace = true }
description = "Event verifier API types and schema"

[[bin]]
name = "schema_generator"
path = "src/bin/schema_generator.rs"

[[bin]]
name = "event-verifier-schema"
path = "src/bin/schema.rs"

[dependencies]
axelar-wasm-std = { workspace = true, features = ["derive"] }
client = { workspace = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
error-stack = { workspace = true }
msgs-derive = { workspace = true }
router-api = { workspace = true }
schemars = "0.8"
serde_json = { workspace = true }

[lints]
workspace = true
