[package]
name = "event-verifier-api"
version = "1.0.0"
rust-version = { workspace = true }
license = "MIT OR Apache-2.0"
edition = { workspace = true }
description = "Event verifier API types and schema"

[[bin]]
name = "event-data-schema"
path = "src/bin/event-data-schema.rs"

[dependencies]
axelar-wasm-std = { workspace = true, features = ["derive"] }
chrono = "0.4"
clap = { version = "4.0", features = ["derive"] }
client = { workspace = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
error-stack = { workspace = true }
goldie = { workspace = true }
msgs-derive = { workspace = true }
schemars = "0.8"
serde_json = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
