[package]
name = "axelarnet-gateway-api"
version = "0.1.0"
rust-version = { workspace = true }
edition = "2021"

[dependencies]
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
router-api = { workspace = true }

[lints]
workspace = true
