[package]
name = "error-utils-derive"
version = "1.0.0"
rust-version = { workspace = true }
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
error-stack = { workspace = true }
quote = "1.0.33"
syn = "2.0.29"
thiserror = { workspace = true }

[dev-dependencies]
error-utils = { workspace = true, features = ["contracts"] }

[lints]
workspace = true
