[package]
name = "starknet-types"
version = "1.0.0"
rust-version.workspace = true
edition.workspace = true

[dependencies]
cosmwasm-std = { workspace = true }
router-api = { workspace = true }
ethers-core = { workspace = true }
starknet-core = { workspace = true }
error-stack = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
