[package]
name = "limit"
version = "1.0.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cosmwasm-schema = { workspace = true }

[lints]
workspace = true
