[package]
name = "axelar-core-std"
version = "1.0.0"
edition = { workspace = true }
rust-version = { workspace = true }

[dependencies]
axelar-wasm-std = { workspace = true }
client = { workspace = true }
cosmwasm-std = { workspace = true }
error-stack = { workspace = true }
router-api = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
goldie = { workspace = true }
hex = { workspace = true }
rand = { workspace = true }

[lints]
workspace = true
