[package]
name = "sui-types"
version = "1.0.0"
edition = { workspace = true }
rust-version = { workspace = true }
license = "MIT OR Apache-2.0"

[dependencies]
error-stack = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
rand = { workspace = true }

[lints]
workspace = true
