[package]
name = "aleo-network-config"
version = "0.1.0"
rust-version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
cosmwasm-schema = { workspace = true }
snarkvm-cosmwasm = { workspace = true }
thiserror = { workspace = true }

[lints]
workspace = true
