[package]
name = "interchain-token-service-api"
version = "0.1.0"
rust-version = { workspace = true }
edition = "2021"

[dependencies]
alloy-primitives = { version = "0.7.4", default-features = false }
alloy-sol-types = { version = "0.7.4", default-features = false, features = ["json"] }
axelar-wasm-std = { workspace = true }
axelar-wasm-std-derive = { workspace = true }
cosmwasm-schema = { workspace = true }
cosmwasm-std = { workspace = true }
error-stack = { workspace = true }
flagset = { version = "0.4.3", features = ["serde"] }
report = { workspace = true }
schemars = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
sha3 = { workspace = true }
thiserror = { workspace = true }
valuable = "0.1.0"

[dev-dependencies]
hex = "0.4.3"
rand = "0.8.5"

[lints]
workspace = true
