tm_jsonrpc="http://k8s-devnetit-coresent-3ea294cee9-0949c478b885da8a.elb.us-east-2.amazonaws.com:26657"
tm_grpc="tcp://k8s-devnetit-coresent-3ea294cee9-0949c478b885da8a.elb.us-east-2.amazonaws.com:9090"
event_buffer_cap=10000

[event_processor]
retry_delay = '1s'
retry_max_attempts = 3
stream_timeout = '15s'
stream_buffer_size = 100000

[service_registry]
cosmwasm_contract="axelar1hrpna9v7vs3stzyd4z3xf00676kf78zpe2u5ksvljswn2vnjp3ystlgl4x"

[broadcast]
batch_gas_limit="20000000"
broadcast_interval="1s"
chain_id="devnet-its"
gas_adjustment="2"
gas_price="0.00005uits"
queue_cap="1000"
tx_fetch_interval="1000ms"
tx_fetch_max_retries="15"

[tofnd_config]
batch_gas_limit="10000000"
key_uid="axelar"
party_uid="ampd"
url="http://127.0.0.1:50051"

[[handlers]]
multisig_contract="axelar1466nf3zuxpya8q9emxukd7vftaf6h4psr0a07srl5zw74zh84yjq4687qd"
multisig_prover_contract="axelar1dg5jrt89nddtymjx5pzrvdvdt0m4zl3l2l3ytunl6a0kqd7k8hssryjzzk"
type="XRPLMultisigSigner"

[[handlers]]
chain_name="xrpl"
chain_rpc_url="https://s.devnet.rippletest.net:51234/"
cosmwasm_contract="axelar1m8pkv82eamkvw84w38auduy9r5kqp3hf8gwtykwk6d38augx6dzs53vdsa"
type="XRPLMsgVerifier"

[[handlers]]
cosmwasm_contract="axelar1466nf3zuxpya8q9emxukd7vftaf6h4psr0a07srl5zw74zh84yjq4687qd"
type="MultisigSigner"

[[handlers]]
chain_name="avalanche"
chain_rpc_url="https://api.avax-test.network/ext/bc/C/rpc"
cosmwasm_contract="axelar1qum2tr7hh4y7ruzew68c64myjec0dq2s2njf6waja5t0w879lutqv062tl"
type="EvmMsgVerifier"
