name: Build and push latest docker image

on:
  push:
    branches:
      - main
      - feat/ghaction-ecr-build

jobs:
  build-and-push-latest-docker-image:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
    runs-on: ${{ matrix.os }}
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: nelonoel/branch-name@v1.0.1

      - name: fetch tags
        run: |
          git fetch --unshallow

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/ghwf-${{ github.event.repository.name }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build docker image
        run: |
          docker build -t axelar/ampd -f ampd/Dockerfile .

      - name: Push to ECR
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          REPOSITORY: axelar-amplifier
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker image tag axelar/ampd "${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}"
          docker push "${REGISTRY}/${REPOSITORY}:${IMAGE_TAG}"
