name: Basic

on:
  pull_request:

jobs:
  check_description:
    runs-on: ubuntu-22.04
    steps:
      - name: Check Pull Request Description
        env:
          DESCRIPTION: "test description"
        run: |
          if [[ -z "$DESCRIPTION" ]]; then
            echo "Error: Pull request description is empty."
            exit 1
          fi
