name: Security Audit

# This workflow runs cargo-audit to check for known security vulnerabilities
# in project dependencies using the RustSec Advisory Database.
#
# The workflow uses cargo-audit v0.21.2 which supports Cargo.lock version 4
# format introduced in Rust 1.86+.
#
# Despite the recommendation in the related audit-check documentation (https://github.com/rustsec/audit-check?tab=readme-ov-file#audit-changes),
# this does not restrict the check to just when Cargo.toml or Cargo.lock files have changed, so retroactive vulnerabilities
# on existing dependencies will be noticed as soon as possible.

on:
  pull_request:
  push:
    branches:
      - main

# Prevent multiple instances of this workflow from running simultaneously
# on the same branch/PR to avoid resource waste
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  security-audit:
    name: Cargo Audit
    runs-on: blacksmith-16vcpu-ubuntu-2204
    steps:
      - name: Checkout repository including submodules
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install stable toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.86.0
          default: true

      # Install cargo-audit explicitly because available github actions don't support Cargo.lock v4 yet
      - name: Install cargo-audit
        uses: baptiste0928/cargo-install@v3
        with:
          crate: cargo-audit
          version: 0.21.2
          locked: true

      - name: Run cargo audit
        run: cargo audit
