[package]
name = "starknet-checked-felt"
version = "1.0.0"
rust-version = { workspace = true }
edition = { workspace = true }

[dependencies]
alloy-primitives = { workspace = true }
error-stack = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
starknet-types-core = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
axelar-wasm-std = { workspace = true }

[lints]
workspace = true
